-- AGREGAR VÍNCULO CON TALLER PARA MODERACIÓN
ALTER TABLE social_posts ADD COLUMN IF NOT EXISTS taller_id BIGINT REFERENCES talleres(id) ON DELETE SET NULL;

-- ACTUALIZAR POLÍTICAS PARA MODERACIÓN (OPCIONAL EN ESTE PUNTO, MANEJADO POR LA API VÍA REGLAS DE NEGOCIO)
