-- SCRIPT DE DESBLOQUEO TEMPORAL PARA MIGRACIÓN
-- Corré esto en el SQL Editor para que el script pueda subir los datos

ALTER TABLE talleres DISABLE ROW LEVEL SECURITY;
ALTER TABLE alumnos DISABLE ROW LEVEL SECURITY;
ALTER TABLE profesores DISABLE ROW LEVEL SECURITY;
ALTER TABLE inscripciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE pagos DISABLE ROW LEVEL SECURITY;
ALTER TABLE recursos DISABLE ROW LEVEL SECURITY;
